# Generated by Django 4.2.6 on 2023-10-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MriFiles',
            new_name='MriFile',
        ),
    ]
