# Generated by Django 4.2.6 on 2023-10-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_mrifiles_mrifile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrifile',
            name='name',
        ),
    ]
