# Generated by Django 4.2.6 on 2023-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_mrifile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrifile',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
